### ISSUE TITLE
Colocar link dos vídeos ao lado da agenda depois de realizado

### ISSUE THREAD

**Issue by lflucasferreira** [linuxtips/FiqueEmCasaConf#34]
Sugiro colocar o link de cada transmissão na agenda, desta forma, não precisaríamos ficar procurando no youtube.

**Comment by SheimyRahman** [comment]
Adicionado. Aguardando Analise do PR e Merge

**Comment by somatorio** [comment]
Acho que podemos fechar já que rolou o merge, né?
